name: MATLAB Tests CI

on:
  push:
    branches: [ main, v1 ]
  pull_request:
    branches: [ main, v1 ]
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

jobs:
  build-matlab-tests:    
    name: '[matlab:${{ matrix.matlab_version }}:${{ matrix.os }}:${{ matrix.osqp_type }}]'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        osqp_type: [conda-forge, manual-compilation]
        os: [ubuntu-24.04, windows-latest]
        matlab_version: [R2023b, R2024a, latest]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        channels: conda-forge,robotology

    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.matlab_version }}

    - name: Dependencies
      run: |
        # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
        conda config --remove channels defaults
        # Compilation related dependencies 
        conda install cmake cxx-compiler make ninja pkg-config

    - name: Install osqp (conda-forge)
      if: contains(matrix.osqp_type, 'conda')
      run: |
        conda install libosqp

    - name: Install osqp (manual-compilation, Linux/macOS)
      if: contains(matrix.osqp_type, 'manual') && (contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu'))
      shell: bash -l {0}
      run: |
        git clone https://github.com/osqp/osqp -b v1.0.0
        cd osqp
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DOSQP_BUILD_STATIC_LIB:BOOL=OFF -DQDLDL_BUILD_STATIC_LIB:BOOL=OFF -DBUILD_TESTING:BOOL=OFF ..
        ninja install

    - name: Install osqp (manual-compilation, Windows)
      if: contains(matrix.osqp_type, 'manual') && contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        git clone https://github.com/osqp/osqp -b v1.0.0
        cd osqp
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DOSQP_BUILD_STATIC_LIB:BOOL=OFF -DQDLDL_BUILD_STATIC_LIB:BOOL=OFF -DBUILD_TESTING:BOOL=OFF ..
        ninja install

    - name: Print used environment [Conda]
      shell: bash -l {0}
      run: |
        conda list
        env

    - name: Configure [Conda - Linux or  macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING:BOOL=ON ..

    - name: Configure [Conda - Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        mkdir build
        cd build
        cmake  -GNinja -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING:BOOL=ON ..

    - name: Build [Conda - Linux or  macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Build [Conda - Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Install
      run: |
        cd build
        cmake --install . --config ${{ matrix.build_type }}

    # workaround for https://github.com/robotology/robotology-superbuild/issues/64
    - name: Do not use MATLAB's stdc++ to avoid incompatibilities with other libraries
      if: contains(matrix.os, 'ubuntu')
      run:
          echo 'LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6' >> $GITHUB_ENV

    - name: Test - Windows
      if: contains(matrix.os, 'windows')
      shell: bash -l {0}
      run: |
        cd build
        export MATLABPATH=$CONDA_PREFIX/Library/mex
        ctest --output-on-failure -C ${{ matrix.build_type }} -VV . 

    - name: Test - Linux/macOS
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        cd build
        export MATLABPATH=$CONDA_PREFIX/mex
        ctest --output-on-failure -C ${{ matrix.build_type }} -VV . 
